'use strict';

const ASSET_GROUPS = {
	'BLACK POINT FIRE BARN': 5,
	'BLUE POINT SCHOOL': 49,
	'CENTRAL OFFICE': 2,
	'DUNSTAN FIRE BARN': 5,
	'EIGHT CORNERS SCHOOL': 48,
	'MULTIPLE SCHOOLS': 1,
	'NORTH SCARBOROUGH FIRE BARN': 5,
	'OAK HILL FIRE BARN': 5,
	'PINE POINT FIRE BARN': 5,
	'PLEASANT HILL SCHOOL': 47,
	'PLEASANT HILL FIRE BARN': 5,
	'POLICE DEPARTMENT': 3,
	'POLICE COMMAND VAN': 3,
	'POLICE TASK FORCE': 3,
	'PUBLIC WORKS': 4,
	'SCARBOROUGH HIGH SCHOOL': 44,
	'SCARBOROUGH MIDDLE SCHOOL': 46,
	'SCARBOROUGH TOWNHALL': 2,
	'THE CAVE': 2,
	'UNKNOWN/MISSING': '',
	'WENTWORTH SCHOOL': 45
};
